### ISSUE TITLE
Missing script dev

### ISSUE THREAD

**Issue by Bear4** [olitaylor/vlightbox#3]
After install 
`npm install vlightbox`
and 
`npm init`
try: 
`npm run dev` 
and got: 
`npm ERR! missing script: dev`

**Comment by olitaylor** [comment]
@Bear4 I've added the dev script back in, not sure why I removed it... I'll look into it 👍

**Comment by Bear4** [comment]
Sorry I don't know if You checked and repaired script.
But still without luck:
```
λ npm run dev

> vlightbox@2.0.1 dev d:\iview\vlightbox
> node build/dev-server.js

module.js:473
      throw err;
      ^

Error: Cannot find module 'd:\iview\vlightbox\build\dev-server.js'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:453:25)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vlightbox@2.0.1 dev: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vlightbox@2.0.1 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```
